provider:
  name: openfaas

functions:

  go-direct:
    handler: ./
    lang: dockerfile
    image: ttl.sh/openfaas/go-direct:0.0.2
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.zero-duration: 5m

